### ISSUE TITLE
Running a GUI app as a plugin does not work if the command contains spaces

### ISSUE THREAD

**Issue by Yutsuten** [jarun/nnn#1610]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: sway
- [x] Terminal Emulator: alacritty
- [x] Shell: fish
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: None
- [x] Configuration options set: `NNN_PLUG='p:-!&mpv --profile=music "$nnn"'`
- [x] Plugins are installed: No
- [ ] Issue exists on `nnn` master: Haven't checked

#### Exact steps to reproduce the issue

Using v4.7. Tried to reproduce from v4.1.1 to v4.7, nothing works...

The documentation [here](https://github.com/jarun/nnn/tree/master/plugins#run-a-gui-app-as-plugin-) says that I can use this syntax to open an GUI app as plugin: `NNN_PLUG='m:-!&mousepad "$nnn"'`

If I try an app WITHOUT spaces, say `p:-!&anki` or `p:-!&vimiv`, it works as expected.
But if I try `p:-!&vimiv "$nnn"`, pressing the shortcut does nothing. `vimiv` command does accept a path as argument, so if I press `!` or `]`and run `vimiv "$nnn"` manually, it works as expected.
Also if I put a space after a command, like `p:-!&vimiv `, pressing the shortcut does nothing.

For now I have this ugly workaround: `p:-!mpv --profile=music "$nnn" 2>&1 /dev/null &*`

For something so basic to not be working, I worry to be an environment (wayland?) issue, or I being dumb...

**Comment by KlzXS** [comment]
> Using v4.7. Tried to reproduce from v4.1.1 to v4.7, nothing works...

I take it you are installing it using your package manager. There was a change made in f9281c8e that reworks the way commands are invoked as plugins. The wiki reflects the current state of master only.

You should use a different syntax then. `p:-!&vimiv $nnn`, notice the lack of quotes, and `$nnn` must be at the end of the command.

Also remember to update to the new syntax when you update to the next release of `nnn`. Your commands will mostly still work, as long as the filename doesn't require escaping (contains spaces, quotes, the like).

**Comment by jarun** [comment]
This is fixed on master. I will make a release by mid of next month. Having a very busy time.

**Comment by Yutsuten** [comment]
> I take it you are installing it using your package manager.

No, I'm using the static binaries downloaded from [here](https://github.com/jarun/nnn/releases).

> You should use a different syntax then. `p:-!&vimiv $nnn`, notice the lack of quotes, and `$nnn` must be at the end of the command.

No, the problem does not seem to be related with the `$nnn` having double quotes or not. Event WITHOUT it, say `p:-!&vimiv -s sort.shuffle true`, the shortcut still does nothing. The issue is the space, not `$nnn`.

> This is fixed on master.

Compiled and installed master here. Now it is indeed working as expected. I'll close the issue as it is already fixed. Sorry for the trouble, should have tried master before opening the issue...
