### ISSUE TITLE
Questions about selections

### ISSUE THREAD

**Issue by maximbaz** [jarun/nnn#383]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: i3
- [x] Terminal Emulator: kitty
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): N/A
- [x] Issue exists on `nnn` master: yes

Hi there, thanks for this tool, it is quite interesting!

I have a few questions about the selection process, could you please clarify these for me? 

All the quotes are taken from wiki, and the described behavior is on latest `master`.

1. Visual indicators

> Selected files are visually indicated by a + before the entries.

When I press Space a few times, indeed selected files are marked with a `+`. However if I open a new terminal side by side with the current one, and do something there (even a simple `ls`), in the first terminal in the `nnn` all the `+` markers simply disappear. Is that happening because `nnn` is constantly watching file system and re-rendering its display? But if so, is this normal that `+` markers disappear? I understand why they would be gone if you navigate to different folders in `nnn`, but can they be preserved at least while I stay in the current folder and don't do anything in `nnn`?

2. Temporary file

> Absolute paths of the selected files are copied to the temporary file `.selection` in the config directory. The path is shown in the help and configuration screen.

This does happen if I select files using `m` (e.g. by pressing `mjjjm`), but if I select files by pressing `Space` button, this doesn't happen. Is this intentional or a bug, and if intentional, how do I _flush_ the selection made with `Space` to that file?

3. Sharing selections between `nnn` instances

As far as I understand, the reason you use shared folders is to allow multiple `nnn` instances to share a common context. If I select files in one `nnn` instance, I should be able to operate on this selection in another `nnn` instance (is this right?).

However selections don't seem to be merged, e.g. if in the first instance you select a few files (using `mjjjm`), then in the second instance you do see the selection (`M` prints those 3 files), however if in this second `nnn` instance I select more files (again using `mjjjm`) it will _replace_ the selection, not merge that. Is that intended? Why does it matter for `nnn` where the initial file selection has been made, if they share the context?

Or the purpose of this `.selection` file is not to share context, but simply to help building plugins that operate on the current selection? But in that case why do multiple `nnn` instances compete for overriding `.selection` file, wouldn't it make more sense to assign each `nnn` instance a unique temporary folder (e.g. `mktemp -d`) and pass that path to the plugins?

4. Deselecting files

> It's also possible to edit the current selection.
> 
> Deselecting a single file is not implemented because substantial string processing would be required if thousands of files are selected.

I might be missing some context, but these two sentences have a bit opposite meaning... Deselecting a single file _is_ implemented (by pressing `K` and then deleting the line), it just requires more keys to press and more mental energy to spend.

I don't argue that substantial string processing is required if thousands of files are selected, however deselecting files is a real need, and it sounds like there is no faster alternative to perform this task?

I, as a human, will certainly perform slower in pressing `K` and deleting a line than C code doing some array manipulations in memory.

I totally understand that it is tempting to say that `nnn` is fast, but from a user perspective I think what matters a lot more is how fast I can execute my goal, where in this case a goal is to deselect a file that I accidentally selected.

----

I hope you take all the above as a genuine curiosity and feedback, and not as an attack on you in any way! It is truly an interesting application, I'm happy that I stumbled upon it 🙂

**Comment by jarun** [comment]
> Visual indicators

These are not preserved post refresh as it doesn't make sense to mark 1000s of files and remember those. You can always view the selected files using the relevant command.

> how do I flush the selection made with Space to that file?

The flush happens when you run an operation, before that it's just in memory. This is done to reduce file writes after each selection. Currently there is not way to force flush. Maybe we can implement it.

> Sharing selections between nnn instances

The last selection in any instance of `nnn` is written to the file. No merging is involved.

> Deselecting files

Deselecting is not implemented. You can only clear a selection. You can also edit the current selection.

**Comment by jarun** [comment]
Closing this as these have been discussed several times.

**Comment by maximbaz** [comment]
> These are not preserved post refresh as it doesn't make sense to mark 1000s of files and remember those. You can always view the selected files using the relevant command.

I think there are valid cases, `+` indicators help you keep the context of what you are selecting _right now_, it is quite confusing that `+` disappear in the middle of me selecting the files in the current directory.

It feels this could have easily been solved by keeping the files selected in the current directory in a separate buffer, clearing that buffer once current directory changes, and on refresh marking files that are present in the buffer.

Is that something you would consider?

> The last selection in any instance of nnn is written to the file. No merging is involved.

What is the intended purpose of this file?

Allow me to duplicate my questions:

- If the purpose is to share context between running `nnn` instances, why does it matter where the initial file selection has been made (in other words, why `mjjjm` would sometimes override the file and sometimes merge)?

- If the purpose is _not_ to share context between `nnn` instances (but e.g. to allow plugins to operate on selections), why do multiple `nnn` instances compete for overriding `.selection` file, wouldn't it make more sense to assign each `nnn` instance a unique temporary folder (e.g. `mktemp -d`) where it would keep its own state files like `.selection`?

> Deselecting is not implemented. You can only clear a selection. You can also edit the current selection.

I'm afraid you missed the point of my question. Deselection is a real thing people do, users _can_ deselect the file (by editing the current selection), but `nnn` is currently the slowest app of all to perform this operation, because it is not implemented and depends on users to edit the selection file manually. Would you oppose a PR that implements this in code to help people perform deselect operation faster, and if yes could you please elaborate why?

---

Apologies if this has been discussed before, I did find https://github.com/jarun/nnn/issues/263 but I don't think these questions have been answered there, maybe you could at least give me some pointers? Thanks.

**Comment by jarun** [comment]
> it is quite confusing that + disappear in the middle of me selecting the files in the current directory

No, it's not if you don't ignore the fact that you can always view the selection.

> It feels this could have easily been solved by keeping the files selected in the current directory in a separate buffer

That's unbounded memory. And the next time you load due to an event (there can be new files, files can get removed) you'll have to match each file loaded with the files in the buffer. That's non-trivial calculation. In `nnn` we consider extreme cases like directories with 10000 files and then weigh the pros and cons.

> and sometimes merge

There is no merge involved. You expected a merge. I clarified already there is no merge involved.

> why do multiple nnn instances compete for overriding

`.selection` is user-specific and you can only operate in one instance at a time. Please read https://github.com/jarun/nnn/wiki#selection

> Deselection is a real thing people do

That's true. And the 1000s users of `nnn` have probably learnt to deal with not having to deselect frequently considering the advantages.

**Comment by jarun** [comment]
@0xACE @KlzXS @annagrram it's very simple to block event detection when we are in selection mode. If we do that the `+` symbol will not disappear but we will not get directory updates when in selection mode. What do you guys think?

**Comment by jarun** [comment]
I think the reason it is an issue is it's disruptive when someone is doing a selection. At that point (s)he doesn't care about directory updates.

**Comment by jarun** [comment]
I have added this at commit `4c863d9b7b0f63b15006e952e1ca5c81397c9a8e`. Please check the behaviour. I am still not sure about it though.

**Comment by jarun** [comment]
Another note on deseletion - `nnn` supports selection across dirs.

**Comment by jarun** [comment]
To make the behaviour more consistent I have disabled flushing for all/range selection as well. To flush the current selection use the edit, flush selection key. I have made this more consistent at commit 88698b372b65d16a21736c743bfabed32dace273.

**Comment by jarun** [comment]
@maximbaz I have addressed 1 and 2. 1 is subject to review from other devs.

I don't see an issue with 3 because there is no merging involved or expected. You can now flush the intermediate selection as well and it should be available to other instances (when they don't have any in-memory selection already).

You can suggest an implementation for 4 and we can discuss it.

**Comment by 0xACE** [comment]
I'll be very busy so I can't give much input, but as I'm waiting for my food right now I'll do a quickie:

https://github.com/jarun/nnn/commit/88698b372b65d16a21736c743bfabed32dace273
Does this mean that you now have to flush your selection before you try to use plugins that use `.selection`?

https://github.com/jarun/nnn/commit/4c863d9b7b0f63b15006e952e1ca5c81397c9a8e
Does `nnn` no longer refresh when you select file or is it only until you have finished your `m` selection?

**Comment by maximbaz** [comment]
Thanks for taking the time to implement all these ideas and reply to me!

> I think the reason it is an issue is it's disruptive when someone is doing a selection. At that point (s)he doesn't care about directory updates.

The new behavior is definitely more intuitive to me, as my selection doesn't disappear when something changes in the directory. I think your assumption is correct, users most probably don't really care about directory updates while they are selecting some files.

> Does nnn no longer refresh when you select file or is it only until you have finished your m selection?

As I understand, once you press Space, it stops refreshing until you make any action that calls `endselection()`, which can be using `m`, running a plugin, running some action on the selection, or simply changing directories.

> I don't see an issue with 3 because there is no merging involved or expected. You can now flush the intermediate selection as well and it should be available to other instances (when they don't have any in-memory selection already).

I understand better the purpose of `.selection` file and it now makes sense to me why merging is not expected.

> Does this mean that you now have to flush your selection before you try to use plugins that use `.selection`?

As I understand the answer is no, because an action of executing a command still calls `endselection()` which in turn flushes the selection to the file.

> You can suggest an implementation for 4 and we can discuss it.

Right now when you handle file selection, you both flag entries with `FILE_SELECTED` bit and you add them to the buffer using `appendfpath()`, one approach might be to only flag the entries with `FILE_SELECTED` bit and postpone creating the buffer until you actually need it (until you want to flush it to the file?). That way, toggling selection state becomes trivial because you only need to toggle this `FILE_SELECTED` bit. The `resetselind()` function is already going through all files and checking `FILE_SELECTED` bit, so it won't be any worse than that performance-wise to create a function that will once again go through all files, check this bit and prepare the buffer.

This is the first time I looked at the code, so I obviously might be missing some complex scenarios, let me know if the above makes sense 🙂

**Comment by jarun** [comment]
> toggling selection state becomes trivial

As you have noted this only applies to per-dir and someone is going to ask to acros--dir deselection. We also need to ensure we move out of the selection mode when no files are selected (i.e. `nselected` becomes 0). I will need the input from other `nnn` devs if this is indeed required.

**Comment by jarun** [comment]
> one approach might be to only flag the entries with FILE_SELECTED bit and postpone creating the buffer until you actually need it

To do that you'll also have to track directory changes, which I think would make the current code hacky. We have a way to manipulate the selection. Live with it.

**Comment by maximbaz** [comment]
> As you have noted this only applies to per-dir and someone is going to ask to acros--dir deselection.

IMHO deselect is mostly needed when a user accidentally selected something and needs to undo the selection _right away_, across-dir deselect is different and I would even say better handled via `K` (i.e. why would you even go back to the folder when you can just press `K` and kill a line).

I'm happy to wait for other `nnn` devs' opinion, no rush.

> To do that you'll also have to track directory changes, which I think would make the current code hacky.

All we need is to go through `dents` and write the selected ones to the file before `dents` is updated with new entries (i.e. before the `FILE_SELECTED` bits are lost), and as far as I can see that happens in a single place in the code, in `browse() -> populate() -> dentfill()`. I think adding such code somewhere in this pipeline would be enough?

> I have added this [block event detection when we are in selection mode] at commit 4c863d9. Please check the behaviour. I am still not sure about it though.

I've been using this throughout the evening, I must admit this is not solving the issue, unfortunately, or I haven't learned the proper way of doing this in `nnn`.

Say I am cleaning up my `~/Downloads` dir. I go in a random order, mark some files with Space that I want to delete, press `p` or `Enter` to view files I'm unsure about before marking them for deletion as well. Every time I'm back from viewing the file, all `+` indicators are gone, which is very very confusing. It is very tiring to consult `M` every time to see if I already selected a given file or not.

If the files are marked with `FILE_SELECTED` bit anyway, is there something that prevents us from adding a `+` marker in front of them after refresh?

**Comment by jarun** [comment]
> All we need is to go through dents and write the selected ones to the file before dents is updated with new entries

I am not worried about writing the selected list, but about tracking directory changes. That can happen in tons of ways and we can't add this check everywhere. It will litter the code.

> I've been using this throughout the evening, I must admit this is not solving the issue

This is fixed in commit 61048258a70a2d8796defe3e02a98022d40d6358. Please try and confirm.

> If the files are marked with FILE_SELECTED bit anyway, is there something that prevents us from adding a + marker in front of them after refresh?

Yes, because the files are read unsorted when you refresh a directory and the markers aren't valid anymore.

**Comment by maximbaz** [comment]
> I am not worried about writing the selected list, but about tracking directory changes. That can happen in tons of ways and we can't add this check everywhere.

Oh I see what you mean, I was thinking of changing directories (as in `cd`), not about changing contents within the directory.

However given that now we don't listen on directory updates while we are in selection mode, we don't really need to track directory changes, we can trust that `FILE_SELECTED` bits are valid on all `dents` entries?

> This is fixed in commit 6104825. Please try and confirm.

Confirmed, thanks! 👍 

> Yes, because the files are read unsorted when you refresh a directory and the markers aren't valid anymore.

I see...

**Comment by jarun** [comment]
> we don't really need to track directory changes

When you navigate away from the current dir (which can be done in a number of ways), you'll have to write the list of selected files. Because the memory would be reused when you load another directory. That's the issue.

**Comment by jarun** [comment]
@0xACE I missed your msg earlier.

> Does this mean that you now have to flush your selection before you try to use plugins that use .selection?

No, you don't. It will flush before any operation as it does now.

> Does nnn no longer refresh when you select file or is it only until you have finished your m selection?

It's till you complete selection. The events are still fed, only they don't reflect during the period of selection.

**Comment by jarun** [comment]
For future reference, I drafted a inode hash implementation at commit 547d87bfc2caf276dd1bcb943677a0ca306c602d. Please read the notes. If we try to extend this the memory requirements are going to be significant in `nnn` standards.
